### ISSUE TITLE
Failed to install addin Cake.ClickTwice

### ISSUE THREAD

**Issue by gmkado** [agc93/ClickTwice#9]
Using .NET framework 4.7.2 on a WPF project

build.cake preprocessor directive:
```
#addin nuget:?package=Cake.ClickTwice&version=0.1.1
```

and get this error:

```
Error: Failed to install addin 'Cake.ClickTwice'.
```

The diagnostics logs weren't particularly helpful but I'll put them here anyways:
```
Error: Cake.Core.CakeException: Failed to install addin 'Cake.ClickTwice'.
   at Cake.Core.Scripting.ScriptProcessor.InstallAddins(IReadOnlyCollection`1 addins, DirectoryPath installPath) in C:\projects\cake\src\Cake.Core\Scripting\ScriptProcessor.cs:line 109        
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath) in C:\projects\cake\src\Cake.Core\Scripting\ScriptRunner.cs:line 106
   at Cake.Features.Building.BuildFeature.RunCore(IRemainingArguments arguments, BuildFeatureSettings settings) in C:\projects\cake\src\Cake\Features\Building\BuildFeature.cs:line 99
   at Cake.Features.Building.BuildFeature.Run(IRemainingArguments arguments, BuildFeatureSettings settings) in C:\projects\cake\src\Cake\Features\Building\BuildFeature.cs:line 49
   at Cake.Commands.DefaultCommand.Execute(CommandContext context, DefaultCommandSettings settings) in C:\projects\cake\src\Cake\Commands\DefaultCommand.cs:line 72
```

I also tried using the pre-release version, same thing happened.  I noticed the last supported version on the cake documentation is pretty old:
Supported Cake Versions
Versions: 0.19.5 - 0.21.1 

Is this project no longer being maintained?

**Comment by Jackhammer88** [comment]
I also have this issue. Is there any solution?

**Comment by leszekrogowski** [comment]
I've updated the project to work with Cake 2.0.0. It's available under my fork. Unfortunately, we'd need to build the packages on your own and put them on your private NuGet.
